site_name: VMWARE CROSSFIRE FARMING
site_description: Setup instructions to run CrossFire on a Virtual Machine using VMWare.
site_author: AirCh3ats
copyright: 'Copyright &copy; 2021 AirCheats'
site_url: 'https://aircheats.github.io/vmware-cf-guide'
theme:
  name: material
  palette:
    primary: deep purple
  logo: 'https://raw.githubusercontent.com/aircheats/vmware-cf-guide/main/assets/img/icon.png'
  favicon: 'https://raw.githubusercontent.com/aircheats/vmware-cf-guide/main/assets/img/icon.png'
icon:
  logo: material/book-open-variant
  repo: material/git
extra:
  manifest: webapp.manifest
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aircheats
docs_dir: docs/
site_dir: build/
extra_javascript:
  - js/extra.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all

nav:
  - Home: index.md
  - Welcome: welcome.md
  - Getting Started: start.md
  - VMWare:
      - Creating a VM: vmware/create-vm.md
      - Bypass Vmware:
          - Updating VM Config: vmware/vm-config.md
          - Registry Patch for VM: vmware/reg-vm.md
  - CrossFire AFK BOT: crossfire/afk-cf.md
plugins:
    - mkdocs-video
